spring:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
  datasource:
    driver-class-name: org.postgresql.Driver
  flyway:
    baseline-on-migrate: true
    enabled: true
logging:
  level:
    org.springframework.web: DEBUG
server:
  hostname: localhost
  port: ${PORT:8080}
mail:
  server:
    host: smtp.gmail.com
    port: 587
    #    port: 465
    username: testsendmail1970@gmail.com
    password: xajnverxoiafltty
    #    password: ${hidden.email.password}
    properties:mail:smtp: auth=true
    properties:mail:smtp:starttls: enable=true