spring:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
  datasource:
    driver-class-name: org.postgresql.Driver
  flyway:
    baseline-on-migrate: true
    enabled: true
logging:
  level:
    org.springframework.web: DEBUG
server:
  hostname: localhost
  port: ${PORT:8080}